services:


  # gateway
  api-gateway:
    build: ./TrueCode.ApiGateway
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
  
  # finance service
  finance-service:
    build: ./TrueCode.FinanceService
    environment:
      - ASPNETCORE_URLS=http://+:8084
    ports:
      - "8084:8084"
  
  # user service
  user-service:
    build: ./TrueCode.UserService
    environment:
      - ASPNETCORE_URLS=http://+:8083
    ports:
      - "8083:8083" 
        
  # filler service
  currency-filler-service:
    build: ./TrueCode.CurrencyFillerService
  




